name: Build KeyboardRounded RootHide

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.10
        with:
          theos-src: 'waruhachi/theos'
          theos-branch: 'main'
          sdks-src: 'waruhachi/sdks'
          sdks-branch: 'main'

      - name: Setup RootHide Theos
        run: |
          git clone --depth 1 https://github.com/roothide/theos.git roothide-theos
          rm -rf "$THEOS"
          mv roothide-theos "$THEOS"

      - name: Build
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardRounded-RootHide
          path: packages/*.deb
